# Security Configuration

# Differential Privacy Settings
differential_privacy:
  enabled: true
  epsilon: 1.0
  delta: 1e-5
  noise_multiplier: 1.1
  max_grad_norm: 1.0

# Encryption Settings
encryption:
  enabled: true
  algorithm: fernet
  key_derivation:
    iterations: 100000
    salt_length: 16

# Secure Aggregation
secure_aggregation:
  enabled: true
  similarity_threshold: 0.8
  byzantine_tolerance: 0.1