# Training Configuration

# General Training Parameters
epochs: 100
batch_size: 128
validation_split: 0.2
shuffle: true

# Optimizer Settings
optimizer:
  name: adam
  learning_rate: 0.001
  beta_1: 0.9
  beta_2: 0.999
  epsilon: 1e-7

# Loss Function
loss:
  name: binary_crossentropy
  weight_decay: 0.0001

# Data Augmentation
augmentation:
  enabled: true
  rotation_range: 20
  width_shift_range: 0.2
  height_shift_range: 0.2
  horizontal_flip: true